WebUI/Controllers/JobAdvertController.cs
using DataAccess.Context;
using Domain.Model;
using Domain.Model.Enum;
using Domain.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using WebUI.Extensions;

namespace WebUI.Controllers;

//[Authorize]
public class JobAdvertController : BaseController
{
    private readonly UserDbContext _context;
    private readonly UserManager<ApplicationUser> _userManager;
    private const int _pageLimit = 6;
    public JobAdvertController(
        UserDbContext context,
        UserManager<ApplicationUser> userManager
        )
    {
        _context = context;
        _userManager = userManager;
    }

    [HttpPost]
    public async Task<IActionResult> Apply([FromForm] int AdvertId)
    {
        try
        {
            if (!User.Identity.IsAuthenticated)
            {
                Notification("Başvuru özelliğini kullanmak için lütfen giriş yapınız", NotificationType.Info);
                return Redirect($"/Account/LoginUser");
            }

            var advert = await _context.Adverts.FirstOrDefaultAsync(x => x.Id == AdvertId);

            var u = await _userManager.GetUserAsync(User);
            var user = _context.Users.Where(x => x.Id == u.Id).FirstOrDefault();

            if (user == null)
            {
                Notification("Kullanıcı bulunamadı, lütfen giriş yapın!", NotificationType.Error);
                return Redirect($"/Account/LoginUser");
            }

            if (user.Type == ApplicationUserType.PHARMACY)
            {
                Notification("Başvuru özelliği eczaneler için geçerli değil, sadece kullanıcılar içindir", NotificationType.Info);
                return Redirect($"/JobAdvert/Detail/{AdvertId}");
            }

            var applyCheck = _context.Applies.Where(x => x.ApplicantUserId == user.Id && x.AdvertId == AdvertId).FirstOrDefault();
            if (applyCheck != null)
            {
                // TODO: Bir ilana birden fazla başvuru olacak mı ?
                Notification("Bir ilana sadece bir kere başvuruda bulunabilirsiniz", NotificationType.Info);
                return Redirect($"/JobAdvert/Detail/{AdvertId}");
            }

            var resumeCheck = _context.Users.Where(x => x.Id == user.Id && x.ActiveResumeId != null).FirstOrDefault();
            if (resumeCheck == null)
            {
                Notification("İlana başvurmak için özgeçmişinizi sisteme ekleyiniz", NotificationType.Info);
                return Redirect($"/JobAdvert/Detail/{AdvertId}");
            }

            Apply apply = new()
            {
                AdvertId = advert.Id,
                ApplicantUserId = user.Id,
                ApplyDate = DateTime.Now,
                CurrentResumeId = (int)user.ActiveResumeId!,
            };
            await _context.AddAsync(apply);
            await _context.SaveChangesAsync();

            Notification("İlana başarıyla başvuruldu", NotificationType.Success);
            return Redirect($"/JobAdvert/Detail/{AdvertId}");
        }
        catch (Exception ex)
        {
            Notification("İlana başvururken bir hata meydana geldi!", NotificationType.Error);
            return Redirect($"/JobAdvert/Detail/{AdvertId}");
        }
    }

    public IActionResult Detail(int id)
    {
        var model = _context.Adverts
            .Include(x => x.ApplicationUser)
            .Where(x => x.Id == id && x.IsActive)
            .FirstOrDefault();
        if (model == null)
        {
            return Redirect("/Error/ErrorHandler?statusCode=404");
        }
        ViewBag.AdvertId = model?.Id;
        return View(model);
    }

    public IActionResult Technician([FromQuery] int page = 1)
    {
        var model = _context.Adverts
            .Include(x => x.ApplicationUser)
            .Where(x => x.Type == AdvertType.TECHNICIAN && x.IsActive)
            .OrderByDescending(x => x.CreateDate)
            .Skip((page - 1) * _pageLimit)
            .Take(_pageLimit)
            .ToList();
        var modelCount = _context.Adverts
            .Where(x => x.Type == AdvertType.TECHNICIAN && x.IsActive)
            .Count();
        ViewBag.Page = page;
        ViewBag.PageCount = modelCount % _pageLimit == 0 ? (modelCount / _pageLimit) : (modelCount / _pageLimit + 1);
        return View(model);
    }

    public IActionResult Dermocosmetic([FromQuery] int page = 1)
    {
        var model = _context.Adverts
            .Include(x => x.ApplicationUser)
            .Where(x => x.Type == AdvertType.DERMOCOSMETİC && x.IsActive)
            .OrderByDescending(x => x.CreateDate)
            .Skip((page - 1) * _pageLimit)
            .Take(_pageLimit)
            .ToList();
        var modelCount = _context.Adverts
            .Where(x => x.Type == AdvertType.DERMOCOSMETİC && x.IsActive)
            .Count();
        ViewBag.Page = page;
        ViewBag.PageCount = modelCount % _pageLimit == 0 ? (modelCount / _pageLimit) : (modelCount / _pageLimit + 1);
        return View(model);
    }

    public IActionResult Intern([FromQuery] int page = 1)
    {
        var model = _context.Adverts
            .Include(x => x.ApplicationUser)
            .Where(x => x.Type == AdvertType.INTERN && x.IsActive)
            .OrderByDescending(x => x.CreateDate)
            .Skip((page - 1) * _pageLimit)
            .Take(_pageLimit)
            .ToList();
        var modelCount = _context.Adverts
            .Where(x => x.Type == AdvertType.INTERN && x.IsActive)
            .Count();
        ViewBag.Page = page;
        ViewBag.PageCount = modelCount % _pageLimit == 0 ? (modelCount / _pageLimit) : (modelCount / _pageLimit + 1);
        return View(model);
    }
    public IActionResult License([FromQuery] int page = 1)
    {
        var model = _context.Adverts
            .Include(x => x.ApplicationUser)
            .Where(x => x.Type == AdvertType.LICENSE && x.IsActive)
            .OrderByDescending(x => x.CreateDate)
            .Skip((page - 1) * _pageLimit)
            .Take(_pageLimit)
            .ToList();
        var modelCount = _context.Adverts
            .Where(x => x.Type == AdvertType.LICENSE && x.IsActive)
            .Count();
        ViewBag.Page = page;
        ViewBag.PageCount = modelCount % _pageLimit == 0 ? (modelCount / _pageLimit) : (modelCount / _pageLimit + 1);
        return View(model);
    }

    public IActionResult OtherAds([FromQuery] int page = 1)
    {
        var model = _context.Adverts
            .Include(x => x.ApplicationUser)
            .Where(x => x.Type == AdvertType.OTHER && x.IsActive)
            .OrderByDescending(x => x.CreateDate)
            .Skip((page - 1) * _pageLimit)
            .Take(_pageLimit)
            .ToList();
        var modelCount = _context.Adverts
            .Where(x => x.Type == AdvertType.OTHER && x.IsActive)
            .Count();
        ViewBag.Page = page;
        ViewBag.PageCount = modelCount % _pageLimit == 0 ? (modelCount / _pageLimit) : (modelCount / _pageLimit + 1);
        return View(model);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

WebUI/Views/Shared/_AdvertComponentPartial.cshtml
@using Core.Helper;
@using Domain.Model;
@using System.Globalization;
@model Advert

@if (Model != null)
{
    <div class="single-blog-post">
        <div class="row">
            <div class="col-lg-5 col-md-8 pright">
                <div class="img-holder">
                    <img src="~/images/logoadvertt.png" alt="Awesome Image">
                    <div class="published-date">
                        <h3>@Model.CreateDate.ToString("dd MMMM", CultureInfo.CreateSpecificCulture("tr-TR"))</h3>
                    </div>
                    <div class="overlay-style-one">
                        <div class="box">
                            <div class="content">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <div style="background-color:#ff2b58; padding:5px; height:40px;"><span style="color:white; font-size:19px; font-weight:bold; text-transform:capitalize;     line-height: 34px;">@Model.ApplicationUser.PharmacyName</span></div>
                                }
                                else
                                {
                                    <div style="background-color:#ff2b58; padding:5px; height:40px;"><span style="color:white; font-size:19px; font-weight:bold; text-transform:capitalize;     line-height: 34px;">@(StringHelper.ToCensoredAdvertTitle(Model.ApplicationUser.PharmacyName))</span></div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-7 col-md-8 pleft">
                <div class="text-holder">
                    <a href="@Url.Action("Detail","JobAdvert", new {id=Model.Id})">
                        <h3 class="blog-title">@Model.Title</h3>
                    </a>
                    <div class="text">
                        <p>@Model.Description</p>
                    </div>
                    <div class="meta-info clearfix">
                        <div class="left pull-left">
                            <ul class="post-info">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <li><b>Eczane İsmi: </b>@Model.ApplicationUser.PharmacyName</li>
                                }
                                else
                                {
                                    <li><b>Eczane İsmi: </b>@(StringHelper.ToCensoredAdvertTitle(Model.ApplicationUser.PharmacyName))</li>
                                }
                                <br />
                                <li><b>Konum: </b>@(ProvinceHelper.GetProvinceName(Convert.ToInt32(Model.ApplicationUser?.Province ?? "1"))), @Model.ApplicationUser?.District</li>
                                @*<li><a href="#">Eczane, Teknisyen</a></li>*@
                            </ul>
                        </div>
                        <div class="right pull-right">
                            <a class="thm-btn bg-clr1" style="padding:0px 8px;" type="submit" href="@Url.Action("Detail","JobAdvert", new {id=Model.Id})" data-loading-text="Please wait...">İncele</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

WebUI/Views/Shared/_BoostedAdvertCardPartial.cshtml
@using Core.Helper;
@using Domain.Model;
@using System.Globalization;
@model Advert


@if (Model != null)
{
    <div class="item" style="margin:0 10px;">
        <div class="single-blog-post">
            <div class="img-holder" style="display:flex; justify-content:center;">
                <img src="~/images/logoadvert.png" alt="İlan Fotoğrafı" style="margin-top:50px;">
                <div class="published-date" style="top:0; left:0;">
                    <h3>@Model.CreateDate.ToString("dd MMMM", CultureInfo.CreateSpecificCulture("tr-TR"))</h3>
                </div>
                <div class="overlay-style-one">
                </div>
            </div>
            <div class="text-holder" style="border-left:1px solid #dcdcdc;">
                <a href="@Url.Action("Detail", "JobAdvert", new { id = Model.Id })">
                    <h3 class="blog-title text-center">@Model.Title</h3>
                </a>
                <div class="text">
                    <p>@Model.Description</p>
                </div>
                <div class="meta-info clearfix" style="margin-left:0;">
                    <div class="left pull-left">
                        <ul class="post-info">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li style="border:none; padding-bottom:3px;"><b>Eczane İsmi: </b>@Model.ApplicationUser?.PharmacyName</li>
                            }
                            else
                            {
                                <li style="border:none; padding-bottom:3px;"><b>Eczane İsmi: </b>@(StringHelper.ToCensoredAdvertTitle(Model.ApplicationUser?.PharmacyName))</li>
                            }
                            <li><b>Konum: </b>@(ProvinceHelper.GetProvinceName(Convert.ToInt32(Model.ApplicationUser?.Province ?? "1"))), @Model.ApplicationUser?.District</li>
                        </ul>
                    </div>
                    @*   <div class="right pull-right">
                <a class="post-share" href="#">
                <i class="fa fa-share-alt" aria-hidden="true"></i>
                </a>
                </div> *@
                </div>
            </div>
        </div>
    </div>
}

WebUI/Views/Shared/_LayoutPharmacy.cshtml
@using Core.Helper;
@using Domain.Model;
@using Microsoft.AspNetCore.Identity;

@inject UserManager<ApplicationUser> UserManager

@{
    var u = await UserManager.GetUserAsync(User);
    var user = UserManager.Users.SingleOrDefault(x => x.Email == u.Email);
}

<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Farma Kariyer - İlk ve tek eczaneler arası kariyer platformu" />
    <title>@ViewData["Title"] - Karma Kariyer Profil</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/user/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/user/css/adminlte.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.3/dist/sweetalert2.min.css" integrity="sha256-sWZjHQiY9fvheUAOoxrszw9Wphl3zqfVaz1kZKEvot8=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!--select2-->
    <link href="https://cdn.jsdelivr.net/npm/select2@@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
        </nav>
        <aside class="main-sidebar elevation-4" style="background-color:#2b2c36;">
            <a href="@Url.Action("Index","Home")" class="brand-link">
                <div style="display:flex; justify-content:center;" class=" elevation-3">
                    <img src="~/images/logo1.png" alt="AdminLTE Logo" class="brand-image" style="opacity: .8">
                </div>
            </a>
            <div class="sidebar">
                <div class="user-panel mt-3 pb-2 d-flex">
                    <div class="image">
                        <img src="@(Url.Content(UserHelper.UserPhotoOrDefault(user?.PhotoPath)))" style="border:3px solid #ff2b58; border-radius:50%; height:34px; width: 34px;" />
                    </div>
                    <div class="info">
                        <a href="/Pharmacy/Account/Profile" class="d-block">@user?.Name @user?.Surname</a>
                    </div>
               </div>
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Home")" class="nav-link">
                                <i class="nav-icon fas fa-home"></i>
                                <p>
                                    Anasayfaya dön
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/Pharmacy/Account/Profile" class="nav-link">
                                <i class="nav-icon fa-solid fa-user"></i>
                                <p>
                                    Profil
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fa-solid fa-address-card"></i>
                                <p>
                                    İlan Yönetimi
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview" style="display: none;">  
                                <li class="nav-item">
                                    <a href="/Pharmacy/Advert/Create" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Yeni İlan</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="/Pharmacy/Advert/List" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>İlanlarım</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="/Pharmacy/Account/Packages" class="nav-link">
                                <i class="fa-solid fa-cart-shopping  nav-icon"></i>
                                <p>
                                    Paketler
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Contact","Home")" class="nav-link">
                                <i class="nav-icon fa-solid fa-question"></i>
                                <p>
                                    Yardım
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Logout", "Account")" class="nav-link">
                                <i class="nav-icon fa-solid fa-right-from-bracket"></i>
                                <p>
                                    Çıkış Yap
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">@ViewData["Title"]</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")" style="color:#ff2b58;">Anasayfa</a></li>
                                <li class="breadcrumb-item active">@ViewData["Title"]</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            @RenderBody()
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
                Farma Kariyer
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2024 <a href="https://cloudnoyo.com" style="color:#ff2b58;">FarmaKariyer</a></strong> Cloudnoyo Tüm hakları saklıdır.
        </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <!-- Select2 JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.js" integrity="sha512-+k1pnlgt4F1H8L7t3z95o3/KO+o78INEcXTbnoJQ/F2VqDVhWoaiVml/OEHv9HsVgxUaVW+IbiZPUJQfF/YxZw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/user/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/user/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/user/js/adminlte.js"></script>
    @*<script src="~/user/dist/js/adminlte.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.3/dist/sweetalert2.all.min.js" integrity="sha256-t0FDfwj/WoMHIBbmFfuOtZv1wtA977QCfsFR3p1K4No=" crossorigin="anonymous"></script>
    @await Html.PartialAsync("_NotificationPartial")
    @await RenderSectionAsync("Scripts", false)
    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
        var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
        (function () {
            var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
            s1.async = true;
            s1.src = 'https://embed.tawk.to/6537f257a84dd54dc484bd28/1hdh8l9q3';
            s1.charset = 'UTF-8';
            s1.setAttribute('crossorigin', '*');
            s0.parentNode.insertBefore(s1, s0);
        })();
    </script>
    <!--End of Tawk.to Script-->
</body>
</html>

WebUI/Views/Shared/_NotificationPartial.cshtml
<script>@Html.Raw(TempData["notification"]?.ToString())</script>

WebUI/Views/Shared/_PaginationPartial.cshtml
@using Domain.ViewModel.Core;
@model PaginationVM

<div class="row">
    <div class="col-md-12">
        <ul class="post-pagination text-center">
            @if (Model.Page > 1)
            {
                <li>
                    <a href="@Url.Action(Model.Action, Model.Controller, new { page = Model.Page - 1 })">
                        <i class="fa fa-caret-left" aria-hidden="true"></i>
                    </a>
                </li>
            }
            else
            {
                <li>
                    <a>
                        <i class="fa fa-caret-left" aria-hidden="true"></i>
                    </a>
                </li>
            }
            @if (Model.Page > 1)
            {
                <li>
                    <a href="@Url.Action(Model.Action, Model.Controller, new { page = Model.Page - 1 })">@(Model.Page - 1)</a>
                </li>
            }
            <li class="active">
                <a>@Model.Page</a>
            </li>
            @if (Model.Page != Model.PageCount)
            {
                <li>
                    <a href="@Url.Action(Model.Action, Model.Controller, new { page = Model.Page + 1 })">@(Model.Page + 1)</a>
                </li>
            }
            @if (Model.Page != Model.PageCount)
            {
                <li>
                    <a href="@Url.Action(Model.Action, Model.Controller, new { page = Model.Page + 1 })">
                        <i class="fa fa-caret-right" aria-hidden="true"></i>
                    </a>
                </li>
            }
            else
            {
                <li>
                    <a>
                        <i class="fa fa-caret-right" aria-hidden="true"></i>
                    </a>
                </li>
            }
        </ul>
    </div>
</div>